[project]
name = "source-aware-rag-tutor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "llama-index>=0.14.8",
    "llama-index-llms-openai>=0.6.9",
    "python-dotenv>=1.2.1",
]
